# Generated by Django 5.1.4 on 2024-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="estado_civil",
            field=models.CharField(
                choices=[
                    ("solteiro", "Solteiro(a)"),
                    ("casado", "Casado(a)"),
                    ("divorciado", "Divorciado(a)"),
                    ("viuvo", "Viúvo(a)"),
                    ("separado judicialmente", "Separado(a) Judicialmente"),
                    ("uniao estavel", "União Estável"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="seccional_oab",
            field=models.CharField(
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
            ),
        ),
    ]
