# Generated by Django 5.1.4 on 2024-12-19 15:44

from django.db import migrations, models
from apps.utils import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validate_phone],
                    ),
                ),
                ("data_cad", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.CharField(
                        max_length=14,
                        validators=[utils.validate_document],
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("fisica", "Física"), ("juridica", "Jurídica")],
                        max_length=255,
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("cep", models.CharField(blank=True, max_length=9, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=20, null=True)),
                ("genitor", models.CharField(blank=True, max_length=255, null=True)),
                ("genitora", models.CharField(blank=True, max_length=255, null=True)),
                ("profissao", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("separado judicialmente", "Separado(a) Judicialmente"),
                            ("uniao estavel", "União Estável"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "customers",
            },
        ),
    ]
