# Generated by Django 5.1.4 on 2025-03-22 04:09

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='documento',
            field=models.CharField(max_length=14, validators=[utils.utils.validate_document]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[utils.utils.validate_phone]),
        ),
    ]
