# Generated by Django 5.1.4 on 2024-12-11 12:06

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=18, validators=[customers.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[customers.validators.validate_phone]),
        ),
    ]
