# Generated by Django 5.1.4 on 2025-03-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_documento_alter_customer_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
