# Generated by Django 5.1.4 on 2024-12-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_cpf_alter_customer_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cpf',
            new_name='documento',
        ),
    ]
