# Generated by Django 5.1.4 on 2024-12-11 23:36

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_cpf_customer_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='documento',
            field=models.CharField(max_length=14, validators=[customers.validators.validate_document]),
        ),
    ]
