# Generated by Django 5.1.4 on 2024-12-11 12:06

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telefone',
            field=models.CharField(max_length=20, validators=[users.validators.validate_phone]),
        ),
    ]
