# Generated by Django 5.1.4 on 2025-03-22 04:09

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='documento',
            field=models.CharField(max_length=14, validators=[utils.utils.validate_document]),
        ),
        migrations.AlterField(
            model_name='users',
            name='telefone',
            field=models.CharField(max_length=20, validators=[utils.utils.validate_phone]),
        ),
    ]
