# Generated by Django 5.1.4 on 2024-12-11 23:36

from django.db import migrations, models
from apps.utils import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "documento",
                    models.CharField(
                        max_length=14,
                        validators=[utils.validate_document],
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("fisica", "Física"), ("juridica", "Jurídica")],
                        max_length=255,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validate_phone],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "suppliers",
            },
        ),
    ]
