# Generated by Django 5.1.4 on 2024-12-13 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_paymentmethods_alter_suppliers_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_fechamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario_abertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_abertura', to=settings.AUTH_USER_MODEL)),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_fechamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
