# Generated by Django 5.1.4 on 2024-12-14 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_registers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='registers',
            options={'verbose_name': 'Register', 'verbose_name_plural': 'Registers'},
        ),
        migrations.AlterField(
            model_name='registers',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_abertura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registers',
            name='usuario_fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_fechamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='paymentmethods',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='registers',
            table='register',
        ),
    ]
