# Generated by Django 5.1.4 on 2024-12-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_frequencies_alter_registers_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencies',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='registers',
            options={'verbose_name': 'Caixa', 'verbose_name_plural': 'Caixas'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
