# Generated by Django 5.1.4 on 2025-03-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_frequencies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Serviço Prestado',
                'verbose_name_plural': 'Serviços Prestados',
                'db_table': 'provided_services',
            },
        ),
    ]
